### ISSUE TITLE
Regarding citation 

### ISSUE THREAD

**Issue by interactyuvraj** [dnlbauer/WHAM#12]
Hello,

I used your code extensively and wanted to cite it in my paper. Could you please help me do that? Since there is no publication, according to the soft matter journal template, it creates a problem. 

Thanks and Regards
Yuvraj Singh
Dept Of Physics
IISER Tirupati
India

**Comment by dnlbauer** [comment]
Hi,

Glad to hear that this tool was a help for you. Even though there is no publication, there is still a citeable doi you can use:
```
Bauer, D., WHAM - An efficient weighted histogram analysis implementation written in Rust, Zenodo. https://doi.org/10.5281/zenodo.1488597
```
